### ISSUE TITLE
10a. Wyświetlanie panelu statystyk - Analiza scenariusza pod względem kompletności i jasności + feedback

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#14]
Zadanie: Sprawdzanie wymagania funkcjonalnego i scenariusza pod względem kompletności i jasności + komunikacja z zespołem dokumentacji

Link do dokumentu z wymaganiami: https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0
(Z dokumentu będą korzystali także graficy, którzy pracują nad wstępnymi, uproszczonymi widokami oraz przejściami między widokami, które również będziemy później pod kątem zgodności sprawdzać).
(Wszystkie ewentualne zmiany w scenariuszach będą zaznaczane kolorem czerwonym).

W ramach zadania proszę o:
0. Zaznajomienie się z zadaniem
1. Zapoznanie się z wymaganiami funkcjonalnymi aplikacji
2. Dokładne przeczytanie i przeanalizowanie wymienionego w tytule scenariusza
3. Sprawdzić scenariusz pod różnymi kątami: 
    - czy jest on zrozumiały, 
    - czy nie ma w nim jakichś błędów logicznych, 
    - czy opisany sposób działania totalnie nie ma sensu (ma mieć sens :), 
    - czy coś można zrobić lepiej, czy coś zostało pominięte itd. 
4. W razie jakichkolwiek uwag lub niepewności, prośba o zamieszczanie komentarzy w dokumencie, w konkretnym miejscu którego uwaga/niepewność dotyczy i opisanie sytuacji
5. Krótkie i zwięzłe podsumowanie procesu wykonywania zadania, podczas jego zamykania (w komentarzu) .
6. Po zapoznaniu się z zadaniem podanie w komentarzu zadania, czas (najlepiej datę i godzinę) orientacyjnego ostatecznego wykonania zadania. A także aktualizacja tego czasu w razie konieczności za pomocą kolejnego komentarza, wraz z uzasadnieniem.

W razie potrzeby info do PM-ów:
- Testerów @aria.here. 
- Dokumentacji @likusia

**Comment by d-wojtowicz** [comment]
Zadanie wykonam 23.10 (dzisiaj)
