### ISSUE TITLE
Opiniowanie schematu baz danych UML

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#25]
Zadanie dotyczy opiniowania schematu baz danych UML

**Przydatne linki:**
Link do wymagań i scenariuszy: https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0#heading=h.bkmsbbcx2fsq
Link do rozwiniętych wymagań: https://docs.google.com/document/d/1-IEzWlja_oeX4VcJp_UQsPmy97cpo4l09vsWJ-_DXW4/edit?tab=t.0#heading=h.a8ygkmvpd7w4
Link do opisu schematu bazy danych: 
https://docs.google.com/document/d/1u5IPpOg9kyIBA538AxfJyk0HP991Awp0/edit?usp=sharing&ouid=103024165156251261658&rtpof=true&sd=true
Schemat bazy danych:
- ![Image](https://github.com/user-attachments/assets/bf9d55a3-c6fa-4ad0-b292-a111bd0a0eea)

**Co do zrobienia:**
Prośba aby zapoznać się z schematem bazy danych oraz jego opisem, a także mając na względzie scenariusze i wymagania, ocenić zgodność i jakość schematu bazy danych. 
Dokonać odpowiednich komentarzy bądź i sugestii do wstępnego [opisu schematu bazy danych](https://docs.google.com/document/d/1u5IPpOg9kyIBA538AxfJyk0HP991Awp0/edit?usp=sharing&ouid=103024165156251261658&rtpof=true&sd=true).

W razie potrzeby info do PM-ów (discord):
Testerów @aria.here.
Backendowców @_husar_

**Comment by d-wojtowicz** [comment]
Zadanie wykonane dzisiaj (31.10.2024). Zasugerowane prawdopodobnie potrzebne, drobne modyfikacje dotyczące przechowywania danych powiązanych z użytkownikiem, panelem rankingowym oraz statystykami.

**Comment by Dejwero** [comment]
Zadanie wykonane 1.11.2024. Przeanalizowano schemat i opis pod kątem wymagań pożądanych. Zasugerowano uzupełnienie wydarzenia o jedno pole, dodanie ścieżki z preferowanym typem, dodanie przewodnika oraz ostatnich wyszukiwań użytkownika.

**Comment by HubertMarczuk** [comment]
Zadanie wykonano 3.11.2024. Zapoznano się ze schematem bazy danych i przeanalizowano go pod kątem wymagań i scenariuszy. Dodano sugestie odnośnie języka, adresu oraz użytkownika administratora.
