### ISSUE TITLE
Wstepne testowanie aplikacji na środowisku lokalnym - WEB

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#42]
W ramach zadania należało odpalić aplikację webową lokalnie i przetestować jej obecne możliwości.
W zakres zadania wchodzi również ewentualne zapisanie sugestii/obserwacji, w opinii testerów cennych dla dobra projektu (opcjonalnie).
W razie gdyby takie sugestie powstały, prośba o zamieszczenie ich w komentarzu pod zadaniem.

Link do repo: https://github.com/Nawigacja-SGGW/webapp

Jest to task zespołowy (przewiduje że przynajmniej kilka osób będzie wykonywało to samo zadanie), stąd możliwa duża ilość osób przy tasku, jeżeli czujecie że zrobiliście ponad zadanie napiszcie do mnie i coś wymyślimy.

**Comment by d-wojtowicz** [comment]
Zadanie wykonano dzisiaj (2024-11-22).

**WAŻNE:**
1. Obiekty przechowywane w bazie muszą zawierać także pola z wartościami wersji angielskiej (np. wprowadzony Budynek 32 z konkretnym opisem powinien być w wersji EN i PL w bazie danych oraz powinien ładować się w zależności od wybranej preferencji językowej użytkownika). 
Ew. inny sposób na zastosowanie tłumaczeń niż modyfikacja bazy danych (jaki?).
Skutki: Wpływ na wersje językowe w home/objects/:id


**ŚREDNIO WAŻNE:**
1. Podstrona home/map	
Bug: Nadpisanie wartości w wybranej opcji (Location/Destination) inną opcją powoduje zniknięcie nadpisywanej wartości z listy wyboru (Do momentu ponownego odwiedzenia panelu home/map bądź odświeżenia strony)
Moment wykrycia buga: Wybieramy Location: Budynek 34, Destination: Budynek 32. Czyścimy pole Location. Nadpisujemy Destination wartością: Budynek 34. Rezultat – Nie można już wybrać opcji Budynek 32 ani w Location ani w Destination.


**MAŁO WAŻNE:**
1. Podstrona forgot-password
Sugestia: Dodać przycisk umożliwiający powrót do panelu logowania.
Do korekty: Wersja językowa PL zawiera angielskie komunikaty "Invalid email" oraz "If your account exists, you will receive an email with a password change".

2. Podstrona change-password
Sugestia: Dodać przycisk umożliwiający powrót do panelu logowania.
Do korekty: Wersja językowa PL zawiera angielskie komunikaty "Password must be at least 6 characters long.", "Passwords do not match." oraz "Password changed correctly.".

3. Podstrona home/objects
Do korekty: Wersja językowa PL zawiera angielskie przyciski "Details" oraz pasek wyszukiwania z placeholderem „Search”.

4. Podstrona home/map
Do korekty: Wersja językowa PL zawiera angielski przycisk "Search".
Do korekty: Na niektórych rozdzielczościach (Testowano na laptopie o rozdzielczości 1920x1080) aplikacja zawiera pionowy pasek scrollu, który po zjechaniu w dół zostawia biały pasek pod aplikacją:
![image](https://github.com/user-attachments/assets/960f5e7b-e97d-42db-8e64-7196af405c14)


5. Podstrona home/settings
Do korekty: Wersja językowa PL zawiera „Username” zamiast „Nazwa użytkownika”.

**Comment by Student-ka** [comment]
_Michał dostarczył mi informacje dotyczącą jego komentarzy z testowania, po krótce podsumowując:_ 

Wątpliwości propo kwestii:
- poprawność rejestracji / logowania? (pod względem poprawnego sprawdzania danych )
- tłumaczenia na polski / angielski 

oraz

"Backend na dev zwraca błąd, że niepoprawny string do połączenia z bazą danych. Podejrzewam, że o tym wiedzą.

Web bardzo dobrze opisał Dominik, nie mam nic do dodania."

**Comment by Student-ka** [comment]
Komentarze i uwagi zostały przekazane dalej.
