### ISSUE TITLE
Testy manualne Web - II tura

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#44]
Treść zadania
-
- W ramach zadania należy uruchomić aplikację webową lokalnie oraz przetestować jej możliwości względem scenariuszy obejmujących funkcjonalności podstawowe. (Scenariusze od 0 do 5). Skupiamy się tutaj na użytkowniku końcowym i interfejsie.

- W zakres zadania wchodzi również zapisanie sugestii/obserwacji/uwag, wg. opinii testerów cennych dla dobra projektu.
W razie braku powyższych informacja o całkowitej poprawności z wymaganiami.
Prośba o zamieszczenie ich w komentarzu pod zadaniem.

Podział zadań:
- @HubertMarczuk - 0, 1a, 1b , 2a, 2aa
- @Dejwero - 2b, 2c, 3a, 3c, 4a, 
- @martunia880 - 3b, 4b,  4d, 4c, 5

Przydatne linki
-
Link do scenariuszy: https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0#heading=h.bkmsbbcx2fsq
Link do repo: https://github.com/Nawigacja-SGGW/webapp
https://www.figma.com/design/6C7dUvxgOpZMqRNPQcLlHV/Nawigacja---SGGW?node-id=0-1&node-type=canvas&t=VPvGzziq47ljhcl3-0

**Comment by HubertMarczuk** [comment]
Zadanie w toku.

**Comment by Dejwero** [comment]
Scenariusz 2b - wyszukiwarka w widoku mapy nie istnieje, natomiast wyszukiwarka w liście obiektów poprawnie wyszukuje obiekty, jednak nie informuje o nieznalezieniu obiektów.
Scenariusz 2c - sortowanie i filtrowanie nie istnieje, obiekty nie są też domyślnie alfabetycznie posortowane (Budynek 34 znajduje się wyżej na liście niż Budynek 32).
Scenariusz 3a i 3c - panel administracyjny nie istnieje, więc sprawdzenie dodawania i edytowania nie jest możliwe.
Scenariusz 4a - na ten moment logowanie przepuszcza wszystko, sprawdzanie go nie ma sensu.

Na ten moment nie da się wielu rzeczy przetestować, więc zadanie jest w toku.

**Comment by Student-ka** [comment]
Zadanie przedłużone ze względu na zbyt duże braki.
Planowane wznowienie prac w poniedziałek 9.12.2024.
