### ISSUE TITLE
Testy API według schematu endpointów za pomocą Postmana

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#45]
Treść zadania
-

- W ramach zadanka należy przetestować API według schematu endpointów za pomocą Postmana.
- Prośba, aby wszelkie uwagi dokumentować w komentarzach pod zadankiem (w razie kwestii pilnych bezpośrednio do PM-ów Testerów (discord: aria.here.) i Backendu (discord: _husar_)).
- Bycie w gotowości że prawdopodobnie dopiszę do zadanka każdemu jeszcze 1-2 endpointy. Wtedy oczywiście mieć na względzie że je też wypadało by sprawdzić.
- INFO DODATKOWE: W dokumencie ze schematem, niektóre endpointy mają kolory. Tzn że są usuwane/przekształcane/jeszcze nie zrobione, dlatego końcowo nie będziecie w tym tygodniu jeszcze ich sprawdzali.

Podział zadań:
- @Student-ka (przygotowanie gruntu pod zadanie, sprawdzenie możliwości dostępu do wszystkich endpointów, nadzór i komunikacja między PM-ami i zespołami: testerów, backendu)
- @bartoszkonarski 
**Autoryzacja i sesje użytkownika:**
POST /auth/login - Logowanie (wymaga e-maila i hasła, zwraca token JWT).
POST /auth/register - Rejestracja (wymaga e-maila i hasła).
**Użytkownicy:**
GET /all-users - Pobieranie informacji o wszystkich użytkownikach i ich wyszukiwaniach.
**Obiekty:**
GET /objects - Pobieranie informacji o wszystkich obiektach.
GET /single-object - Pobieranie informacji o pojedynczym obiekcie na podstawie ID.
- @d-wojtowicz 
**Autoryzacja i sesje użytkownika:**
POST /auth/login - Logowanie (wymaga e-maila i hasła, zwraca token JWT).
POST /auth/register - Rejestracja (wymaga e-maila i hasła).
_PATCH /auth/reset-password-request - Wysłanie maila z linkiem do resetowania hasła.
PATCH /auth/reset-password - Resetowanie hasła użytkownika po zalogowaniu.
POST /auth/logout - Wylogowanie użytkownika._
**Obiekty:**
GET /objects - Pobieranie informacji o wszystkich obiektach.
GET /single-object - Pobieranie informacji o pojedynczym obiekcie na podstawie ID.
**Użytkownicy:**
GET /all-users - Pobieranie informacji o wszystkich użytkownikach i ich wyszukiwaniach.

Potrzebne linki
-
Link do repo: https://github.com/Nawigacja-SGGW/Backend
Link do schematu endpointów: https://sggwpl-my.sharepoint.com/:w:/g/personal/s208410_sggw_edu_pl/EV8ATxOYaFBPqpZpbonGb2QBi2dqtTvzDckZrs5UGdg20Q?rtime=pTyFgAQS3Ug

Wskazówki do zadania
-

- Korzystajcie z gałęzi dev 
- Po dostep do bazy zgłoście się do Michałą (PM-a devopsow), Dr Nick na githubie, powiedzcie że chcecie dostep do bazy bo robicie testy API i podajcie mu swój publiczny IP.
- W celu połączenia z bazą potrzeba jest zainstalowania sterownika ![Image](https://github.com/user-attachments/assets/174f4503-216a-4eb4-9b16-9af7209ce61d)
Link do pobrania: https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16

Lista wszystkich endpointów:
-
**Autoryzacja i sesje użytkownika:**
POST /auth/login - Logowanie (wymaga e-maila i hasła, zwraca token JWT).
POST /auth/register - Rejestracja (wymaga e-maila i hasła).
PATCH /auth/reset-password-request - Wysłanie maila z linkiem do resetowania hasła.
PATCH /auth/reset-password - Resetowanie hasła użytkownika po zalogowaniu.
POST /auth/logout - Wylogowanie użytkownika.
**Obiekty:**
GET /objects - Pobieranie informacji o wszystkich obiektach.
GET /single-object - Pobieranie informacji o pojedynczym obiekcie na podstawie ID.
**Użytkownicy:**
GET /all-users - Pobieranie informacji o wszystkich użytkownikach i ich wyszukiwaniach.

**Comment by d-wojtowicz** [comment]
Zadanie wykonano dzisiaj (2024-12-02).

**Lista przetestowanych endpointów:**
POST /auth/login - Logowanie (wymaga e-maila i hasła, zwraca token JWT).
POST /auth/register - Rejestracja (wymaga e-maila i hasła).
PATCH /auth/reset-password-request - Wysłanie maila z linkiem do resetowania hasła.
PATCH /auth/reset-password - Resetowanie hasła użytkownika po zalogowaniu.
POST /auth/logout - Wylogowanie użytkownika.
GET /all-users - Pobieranie informacji o wszystkich użytkownikach i ich wyszukiwaniach.
GET /objects - Pobieranie informacji o wszystkich obiektach.
GET /single-object - Pobieranie informacji o pojedynczym obiekcie na podstawie ID.


**1. Uwagi niezwiązane z testami:**

- Przy pierwszym uruchomieniu Backendu na gałęzi **dev** wystąpił problem ze sterownikiem do bazy SQL. Aby rozwiązać problem, konieczne było zainstalowanie sterownika **ODBC Driver 17 for SQL Server**, co pozwoliło na nawiązanie połączenia z bazą. Warto wspomnieć o tym w README. Przed instalacją pojawiał się błąd widoczny na załączonym obrazku:

![image](https://github.com/user-attachments/assets/69e74d36-b52d-4bb8-ae8a-076b3eb8d4e0)




**2. Uwagi związane z testami:**

- Endpointy _/auth/reset-password-request_ i _/auth/reset-password_ w udokumentowanym schemacie endpointów są określone jako **PATCH**, ale ich implementacja świadczy o typie **PUT**. Testowałem je w Postmanie jako PUT, ponieważ PATCH nie działał. Warto poprawić tą informację w schemacie.

- Dla _/auth/reset-password-request_, pomimo poprawnej odpowiedzi o wysłaniu maila, żaden mail nie dociera (domyślam, się, że tymczasowy brak implementacji tej funkcji).



**3. Ogólne wrażenia:**

- Pola typu hasło są poprawnie ukryte w response JSON-ach.

- Statusy kodów odpowiedzi są dobrze opisane.

- Przypadki poprawne i błędne wypełniania _body_ dla request zwracają odpowiednie wyniki i status code'y.




P.S.: Wyeksportowany plik .json schematu testowanych endpointów w Postmanie wraz z uzupełnionymi requestami został przekazany leadowi testerów.

**Comment by d-wojtowicz** [comment]
Postman collection exported file: [Nawigacja.postman_collection.json](https://github.com/user-attachments/files/17984129/Nawigacja.postman_collection.json)

**Comment by bartoszkonarski** [comment]
Potwierdzam sprawdzenie działania endpointów:
POST /auth/login
POST /auth/register
GET /all-users
GET /objects
GET /single-object 
![Image](https://github.com/user-attachments/assets/b961bb86-71ee-4293-9a7b-7928ca6607f8)
![Image](https://github.com/user-attachments/assets/0f30ff78-7aea-4c85-bfcc-4a06e92b06d4)
![Image](https://github.com/user-attachments/assets/72486b5e-7acb-4d6c-b2a0-169534328672)
![Image](https://github.com/user-attachments/assets/445cdca0-3913-4c64-b3a6-1be5f6159a6f)
![Image](https://github.com/user-attachments/assets/2926b611-7025-4e35-83ed-81705869424c)

**Comment by Student-ka** [comment]
Testy zakończone pozytywnie
