### ISSUE TITLE
Testy manualne Mobile - II tura

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#47]
Treść zadania
-
W ramach zadania należy uruchomić aplikację mobilną lokalnie oraz przetestować jej możliwości względem scenariuszy obejmujących funkcjonalności podstawowe. (Scenariusze od 0 do 5). Skupiamy się tutaj na użytkowniku końcowym i interfejsie.

W zakres zadania wchodzi również zapisanie sugestii/obserwacji/uwag, wg. opinii testerów cennych dla dobra projektu.
W razie braku powyższych informacja o całkowitej poprawności z wymaganiami.
Prośba o zamieszczenie ich w komentarzu pod zadaniem.

Podział zadań (scenariuszy):
- @konradmal - 0, 1a, 1b , 2a, 2aa
- @MichalPamieta - 2b, 2c, 3a, 3c, 4a, 
- @agaszady - 3b, 4b,  4d, 4c, 5

Przydatne linki
-
Link do scenariuszy: https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0#heading=h.bkmsbbcx2fsq
Link do repo: https://github.com/Nawigacja-SGGW/mobileapp
Link do figmy: https://www.figma.com/design/6C7dUvxgOpZMqRNPQcLlHV/Nawigacja---SGGW?node-id=0-1&node-type=canvas&t=VPvGzziq47ljhcl3-0

**Comment by konradmal** [comment]
0. Uruchomienie aplikacji:
- w ekranie logowania można wpisać cokolwiek i jestem zalogowany - pola login i hasło nie działają. Brak walidacji. Podobnie podczas rejestracji.
1a. Wyznaczanie trasy:
- nie działa bez Internetu, brak komunikatu,
- nie działa bez włączonej lokalizacji, jest błąd krytyczny,
- poprzez kliknięcie pinezki jest zmiana tylko zmieniony punkt końcowy, nie da się w ten sposób zmienić punktu startowego,
- nie da się zamienić początku z końcem trasy (brak odpowiedniego przycisku do tego),
1b. Nawigowanie:
- wyznacza tylko jedną trasę, bez alternatywnych,
- brak wskazówek do nawigacji,
2a. Wyświetlanie obiektów:
- nie działają zdjęcia (brak zdjęć + nie da się ich przesuwać),
- wszędzie ustawiony numer budynku 49,
- z listy w ogóle nie działają "obiekty" (ustawienia również),
2aa. Wyświetlanie właściwości punktu na mapie:
- Nic się nie dzieje po kliknięciu na mapę, gdzie nie ma pinezki - w ogóle nie działa.

Spoza scenariuszy z tego co zauważyłem, to nie działa:
- co jakiś czas aplikacja się crashuje, trzeba ją wyłączać i włączać na nowo (z "logowaniem"),
- lista obiektów jest ograniczona tylko do kilku pozycji,
- podczas kliknięcia przycisku "PL" w zmianie języka, aplikacja zmienia język na angielski, a dla "EN" na polski. Jest to nieintuicyjne i powinno być na odwrót.

Po naprawie tych błędów proszę o przypisanie mnie do sprawdzenia tych scenariuszy jeszcze raz w celu sprawdzenia poprawek. Przede wszystkim krytyczne błędy, takie jak crashowanie się aplikacji podczas braku lokalizacji, a także zaimplementowanie logiki nawigowania.

**Comment by MichalPamieta** [comment]
Scenariusz 2b. Wyszukiwanie obiektów
Wyszukiwarka znajduje obiekty tylko po nazwie, ale nie wyszukuje po numerze budynku lub jego adresie (według scenariusza powinna być taka możliwość).

Scenariusz 2c. Przeglądanie obiektów (z możliwością sortowania po numerze lub nazwie)
Przeglądanie obiektów nie działa tj. nie da się przejść do listy wszystkich obiektów (nie udało się sprawdzić, ponieważ np. po kliknięciu w menu przycisku "Obiekty" nic się nie dzieje i nie przenosi do widoku listy obiektów)

Scenariusz 3a. Dodawanie obiektów / Scenariusz 3b. Usuwanie obiektów / Scenariusz 3c. Edytowanie obiektów
Niemożliwe do przetestowania - brak panelu administratora (w tym widoków)

Scenariusz 4a. Logowanie
Na ten moment podczas logowania sprawdzane jest wyłącznie czy pola nie są puste (brak walidacji danych czy komunikatu o niepoprawnych danych). Wprowadzenie dowolnych danych i kliknięcie przycisku "zaloguj" umożliwia zalogowanie się i przejście do głównego widoku z mapą. Podpunktu 1c nie udało się przetestować ze względu na brak sprawdzania czy konto na dany email już istnieje. Analogicznie, nie dało się sprawdzić podpunktów 1d, 3a i 4a.

**Comment by MichalPamieta** [comment]
> * podczas kliknięcia przycisku "PL" w zmianie języka, aplikacja zmienia język na angielski, a dla "EN" na polski. Jest to nieintuicyjne i powinno być na odwrót.

To nawet nie do końca o to chodzi, że jest na odwrót.
Możemy ciągle klikać tylko PL lub tylko EN, a wersja i tak będzie się przełączać za każdym razem (na zmianę z PL na EN i odwrotnie). W sensie teraz jest tak, że niezależnie od aktualnie wybranej wersji językowej klikanie PL może przełączać zarówno na wersję polską jak i angielską. Tak samo działa to w przypadku klikania EN.
Oczekiwanym zachowaniem powinno być, że jeśli jestem w wersji po polsku i kliknę PL, to nic nie zmienia (a teraz przełącza też na EN). Analogicznie dla wersji po angielsku i klikaniu EN - jeśli mam apkę po angielsku i kliknę EN to przełącza na polski zamiast nic nie zmieniać.
Aktualnie wybrany język aplikacji powinien nie być klikalny, żeby nie można było go wybrać, ale dało się wybierać tylko spośród innych dostępnych języków.

**Comment by Student-ka** [comment]
Zadanie przedłużone ze względu na zbyt duże braki.
Planowane wznowienie prac w poniedziałek 9.12.2024.
