### ISSUE TITLE
Sprawdzanie ostatecznych wersji widoków funkcjonalności pożądanych

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#48]
Treść zadania
-
W zakres zadania wchodzi:
- Sprawdzenie widoków z ich poprawnością wzgledem scenariuszy obejmujących funkcjonalności **pożądanych**. (Scenariusze od 6 do 8).
- Dokumentacja ewentualnych niezgodności w komentarzu pod zadaniem i zgłoszenie ich do PM-a (tylko gdy niezgodności faktycznie są).
- Dokumentacja zgodności i ewentualnych sugesti dotyczących widoków w komantarzach pod zadaniem i na Figmie.
- Sprawdzanie widoków dotyczy wersji zarówno mobilnej jak i desktopowej.

Podział:
Scenariusz 6a - @HubertMarczuk 
Scenariusz 6b -  @bartoszkonarski 
Scenariusz 7 - @martunia880 
Scenariusz 8 (wersja mobilna) - @konradmal 
Scenariusz 8 (wersja webowa) - @MichalPamieta 

Przydatne linki
-
Link do Figmy z widokami: https://www.figma.com/design/6C7dUvxgOpZMqRNPQcLlHV/Nawigacja---SGGW?node-id=1-2&node-type=canvas&t=zDOOmaPWlFghXYru-0

Llink do scenariuszy:
https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0#heading=h.bkmsbbcx2fsq

Ewentualne wskazówki
-
**- Nie wymagamy widoków Panelu Administracyjnego, jest on generowany automatycznie.**

(Przełączanie widoków na wersje webową/mobilną)
![Image](https://github.com/user-attachments/assets/ed0cb474-2911-441d-99e1-1622d81d72e5)

**Comment by konradmal** [comment]
Scenariusz 8 (wersja mobilna) - potwierdzam poprawność i zgodność widoku ze scenariuszem.

**Comment by MichalPamieta** [comment]
Scenariusz 8 (wersja webowa) - potwierdzam poprawność i zgodność widoków ze scenariuszem.

**Comment by bartoszkonarski** [comment]
Scenariusz 6b - brak widoku w wersji webowej

**Comment by HubertMarczuk** [comment]
Scenariusz 6a - potwierdzam poprawność i zgodność widoków ze scenariuszem (w obu wersjach).

**Comment by martaguza** [comment]
Scenariusz 7- widok web i mobile zgodny z opisem

**Comment by Student-ka** [comment]
"Scenariusz 6b - brak widoku w wersji webowej" - Zgłoszone


Zadanie zakończone
