### ISSUE TITLE
Testy manualne Mobile - III tura

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#49]
Treść zadania
-
W ramach zadania należy uruchomić aplikację mobilną lokalnie oraz przetestować jej możliwości względem scenariuszy obejmujących funkcjonalności podstawowe. (Scenariusze od 0 do 5). Skupiamy się tutaj na użytkowniku końcowym i interfejsie.

W zakres zadania wchodzi również zapisanie sugestii/obserwacji/uwag, wg. opinii testerów cennych dla dobra projektu.
W razie braku powyższych informacja o całkowitej poprawności z wymaganiami.
Prośba o zamieszczenie ich w komentarzu pod zadaniem.

Podział zadań (scenariuszy):
@bartoszkonarski 4b, 4c, 4d
@d-wojtowicz 0, 1a, 1b
@MichalPamieta 2a, 2aa, 2c 
@HubertMarczuk 2b, 4a, 5  

**Uwaga!**
-
- Do odpalenia jest konieczność stworzenia pliku o nazwie **.env** i wrzucenia go do root katalogu projektu.

Niech zawartość pliczku wygląda tak:
EXPO_PUBLIC_API_URL=https://sggw-nawigacja-dev-app-api.azurewebsites.net
EXPO_PUBLIC_MODE=development
- Polecenie: npx @react-native-community/cli doctor
Może być przydatne przy sprawdzaniu co potrzebujecie zainstalować żeby się odpaliło

Przydatne linki
-
Link do scenariuszy: https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0#heading=h.bkmsbbcx2fsq
Link do figmy: https://www.figma.com/design/6C7dUvxgOpZMqRNPQcLlHV/Nawigacja---SGGW?node-id=0-1&node-type=canvas&t=VPvGzziq47ljhcl3-0
Link do repo: https://github.com/Nawigacja-SGGW/mobileapp

**Comment by d-wojtowicz** [comment]
### Scenariusz 0 - **Uruchomienie aplikacji**:
1. _Brak zgodności z punktem scenariusza 2b_ - W przypadku wyłączenia internetu i wejścia do aplikacji, program nie wyświetla komunikatu o konieczności połączenia z internetem, co umożliwia wchodzenie w dalsze opcje np. przy zatwierdzaniu logowania na ekranie użytkownika nic się nie dzieje, a w konsoli pojawia się error:
_ERROR  MapLibre error {TextureViewRend}[Style]: Failed to load tile 14/9150/5400=>14 for source osm: Unable to resolve host "tile.openstreetmap.org": No address associated with hostname {"level": "error", "message": "{TextureViewRend}[Style]: Failed to load tile 14/9150/5400=>14 for source osm: Unable to resolve host \"tile.openstreetmap.org\": No address associated with hostname", "tag": "Mbgl"}_

**Podsumowanie:** Reszta całkowicie zgodna ze scenariuszem. Nie napotkano dodatkowych problemów.

### Scenariusz 1a - **Wyznaczanie trasy do wybranego obiektu wraz z informacją o dystansie oraz przewidywanym czasie przybycia**:
1. _Brak zgodności z warunkiem początkowym oraz z punktem scenariusza 3aa, 3ba_ - niemożliwe jest wyznaczenie trasy z/do punktu wybranego poprzez kliknięcie na mapie (to znaczy punktu, który nie jest obiektem w bazie danych).
2. _Błąd działania wyznaczania trasy_ - W przypadku wyboru punktu startowego, bądź końcowego poprzez kliknięcie jakiejkolwiek opcji z listy ostatnio wyszukiwanych nawigacja nie zadziała poprawnie. Jeżeli użytkownik postąpił w ten sposób tuż po zalogowaniu (tj. wybrał opcję z listy ostatnio wyszukiwanych), to nie zostanie wybrana żadna ścieżka do nawigacji. Jeżeli użytkownik postąpił w ten sposób po wybraniu wcześniej jakiejkolwiek poprawnej ścieżki, to wyświetli nam tą samą ścieżkę co wcześniej, tylko ze zaktualizowanymi danymi tekstowymi dla wybranego obiektu z listy ostatnio wyszukiwanych.
3. _Niezgodność działania wyznaczania trasy związana z punktem scenariusza 4a_ - W przypadku lokalizacji daleko poza kampusem dalej możliwe jest wyznaczenie trasy, a zwłaszcza nawigowanie:

![image](https://github.com/user-attachments/assets/a90fecec-f636-4450-a787-0f144ece87be)


**Podsumowanie:** Reszta całkowicie zgodna ze scenariuszem. Nie napotkano dodatkowych problemów - Wyznaczanie trasy poprzez wybór punktu zaznaczonego na mapie i kliknięcie przycisku "Nawiguj" działa poprawnie. Wyznaczanie trasy poprzez wybór punktów (zarówno startu, jak i destynacji, bądź tylko jednego z nich) działa poprawnie jeśli wybierzemy tylko obiekty (a nie pozycje z listy ostatnio wyszukiwanych).

### Scenariusz 1b - **Nawigowanie użytkownika na podstawie wyznaczonej trasy**:
1. Niezgodność z punktem scenariusza 2a, 2b - wyłączenie lokalizacji nie wpływa na przerwanie nawigacji, zarówno tak jak wykroczenie poza obszar SGGW (wypróbowano nawigację dla zdjęcia w punkcie 3 dla Scenariusza 1a).

**Podsumowanie:** Reszta zgodna ze scenariuszem. Nie znalazłem dodatkowych problemów, ale może być to spowodowane tym, że faktycznie nie było mnie na kampusie, a wiemy jak działa lokalizacja na emulatorze.

### Dodatkowe uwagi:
1. W polu wyszukiwania szukając konkretnych fraz filtruje tylko według nazw obiektów, a lista ostatnio wyszukiwanych obiektów nie zmienia się w oparciu o szukaną zawartość:

![image](https://github.com/user-attachments/assets/8db32d72-7db0-4197-b755-b4624bb9b68b)

2. Może ta informacja przyda się innym testerom. Wiem, że proces developmentu jest tylko tymczasowy ale dla usprawnienia prac nad testowaniem (i nie tylko) bardzo cenne byłoby wcześniejsze, dokładniejsze opisanie procesu przygotowania aplikacji oraz wymogów w readme (tj. wspomnienie o zainstalowaniu android studio; uzupełnieniu ANDROID_PATH; zainstalowaniu JDK, SDK o odpowiedniej wersji; potrzebie postawienia emulatora [dla użytkowników z procesorami AMD trzeba wtedy też dodatkowo włączyć opcję SVM w biosie]). Myślę, że każdemu, kto potrzebowałby odpalić aplikację oszczędziłoby to bardzo dużo czasu. Zwłaszcza, że niestety doctor nie potrafi naprawić wszystkiego fix'em samodzielnie. Z dobrych wiadomości co do doctora - wykrywa błędne Android SDK, ale mimo tego aplikacja się włącza i pozwala na testowanie.

**Comment by MichalPamieta** [comment]
### **Scenariusz 2a - Wyświetlanie obiektów**
1. _Brak zgodności z punktem 1a) scenariusza_ - W przypadku wyszukania obiektu w wyszukiwarce z widoku mapy uruchamiane jest od razu nawigowanie i nie wyświetla obiektu wraz z jego właściwościami. Powinno wyświetlać się tak, jak po kliknięciu w pinezkę.

![Image](https://github.com/user-attachments/assets/d121363b-8b70-45f6-8f6c-24f367b04582)

2. _Częściowa zgodność z punktem 2) scenariusza_ - System nie umieszcza wybranego obiektu na środku ekranu. (Czy to jest dodatkowe? W scenariuszu, w nawiasie dalej jest dopisane, że "lub po prostu na ekranie". Który wariant będzie realizowany?)

**Podsumowanie:** Wyświetlanie obiektów z wyszukiwarki uruchamia od razu nawigowanie (nie wyświetla szczegółów obiektu jak przy kliknięciu w pinezkę). Kliknięcie pinezki nie wyśrodkowuje widoku na niej (opcjonalne?).

### **Scenariusz 2aa - Wyświetlanie właściwości punktu na mapie**
1. _Brak możliwość przetestowania (brak funkcjonalności)_ - Po kliknięciu dowolnego miejsca na mapie nie wyświetla się interfejs wybranego punktu.

**Podsumowanie:** Nie ma możliwości dodania pinezki na mapie.

### **Scenariusz 2c - Przeglądanie obiektów**
1. _Brak możliwości przejścia do nawigowania_ - Przycisk "Nawiguj" nie powoduje przejścia do mapy i uruchomienia funkcjonalności "wyznaczanie trasy". Przycisk jest klikalny (aktywny), ale nie wykonuje żadnej akcji.

2. _**(DOKUMENTACJA)** Rozbieżność w punkcie 3) scenariusza_ - Zgodnie z punktem 3), uruchamiamy "wyświetlanie obiektów wraz z ich właściwościami", ale tam mamy widok pierwszy, a nam raczej chodzi o wyświetlenie tego drugiego (przynajmniej ja to tak rozumiem).

![Image](https://github.com/user-attachments/assets/0aa8e2c3-56ee-4be4-bab1-dd7deb2ef8cc)
![Image](https://github.com/user-attachments/assets/79bfd844-1dab-44ef-9702-593485904992)

**Podsumowanie:** Nie działa przycisk "Nawiguj". Reszta funkcjonalności wykonana zgodnie z założeniami scenariusza, ale należałoby uzupełnić dokumentację.

**Comment by HubertMarczuk** [comment]
### **Scenariusz 2b**
Potwierdzam całkowitą zgodność z wymaganiami.

![467136476_989193526420807_8292475255096942379_n](https://github.com/user-attachments/assets/940602ac-1fae-4405-b29a-1ec50543c73b)

![466638780_589801943907726_2161029281885202123_n](https://github.com/user-attachments/assets/5a59d699-b2ae-4983-a039-786ec505eea9)

![467482379_2451266381890970_171247266439521336_n](https://github.com/user-attachments/assets/46ed8354-9430-43d4-ad46-b485d944be09)


### **Scenariusz 4a**
Na ten moment logowanie przepuszcza jakąkolwiek niepustą zawartość pół z e-mailem oraz hasłem, także prawie na pewno ich nie weryfikuje.

![462576601_1306753913974098_2485822449580981806_n](https://github.com/user-attachments/assets/ad76d781-b80b-47fe-b91a-4991db89be77)

Sprawdzenie scenariusza w punktach 1c) oraz 1d) na ten moment jest niemożliwe.

Punkty 2a), 3a) oraz 4a) również są nie do sprawdzenia z racji tego, że system przepuszcza kombinację każdych niepustych pól.

Reszta zgodna z wymaganiami.


### **Scenariusz 5**
Wszystko działa tak jak powinno, ale jest jedna rozbieżność w stosunku scenariusza: po zatwierdzeniu wyboru języka przyciskiem "Zapisz" system nie wraca do widoku głównego ustawień. Moim zdaniem ten powrót jest niepotrzebny i bardziej nieintuicyjny niż tak jest teraz (powrót manualny jest moim zdaniem bardziej intuicyjny dla użytkownika). Rozważyłbym w tym wypadku zmianę scenariusza, zamiast sposobu działania aktualnej wersji aplikacji.

![462566340_3873908776190885_8451057495337706237_n](https://github.com/user-attachments/assets/6f178a80-7737-4667-bfc7-d3ec7ab0bade)

**Comment by bartoszkonarski** [comment]
**Niewymienione punkty scenariuszy działają poprawnie, poniżej znalezione nieprawidłowości.**

### **Scenariusz 4b. Wylogowanie:** 

> 2) System wyświetla okno z pytaniem, czy na pewno się wylogować z konta. Użytkownik potwierdza.

Niezgodność ze scenariuszem, system nie wyświetla okna z pytaniem o potwierdzenie wylogowania

> 3) System informuje o pomyślnym wylogowaniu z konta i przechodzi do funkcjonalności ‘Przeprowadzanie autentykacji i autoryzacji użytkowników’.

Częściowa zgodność ze scenariuszem, aplikacja przechodzi do poprawnej funkcjonalności, jednak nie informuje o pomyślnym wylogowaniu z konta

> 3a) Co, jeżeli wylogowanie się nie powiedzie? (np. brak Internetu) Wówczas system pozostaje w bieżącej sesji. Tak samo błąd systemu, utrata połączenia z serwerem.

Niezgodność ze scenariuszem, brak internetu nie wpływa na zachowanie funkcjonalności

### **Scenariusz 4c. Rejestracja:** 

> 2) System wyświetla formularz z danymi (adres e-mail, hasło, ponów hasło) oraz przycisk do zatwierdzenia. Użytkownik wprowadza dane, a system na bieżąco je weryfikuje. Jeśli wprowadzone dane są poprawne, system umożliwia kliknięcie przycisku do zatwierdzenia formularza.

Niezgodność ze scenariuszem, brak walidacji wprowadzanych danych "live", przycisk zatwierdzenia formularza jest cały czas aktywny

> 2a) Wprowadzone dane są niepoprawne.

Niezgodność ze scenariuszem, formularz dopuszcza wprowadzanie wartości łamiących wymienione reguły.

> 3a) System weryfikuje dane użytkownika. Konto na dany adres e-mail jest już zarejestrowane. System umożliwia przejście do opcji ‘przeprowadzanie autentykacji i autoryzacji użytkowników’ lub ‘zapomnienie hasła’.

Niezgodnośc ze scenariuszem, formularz akceptuje wielokrotne podanie tego samego adresu email

### **Scenariusz 4d. Zapomnienie hasła**

Niezgodność ze scenariuszem, funkcjonalność nie waliduje wprowadzonego adresu email, a także nie wysyła linku do formularza zmiany hasła (co uniemożliwia sprawdzenie pozostałych punktów scenariusza)
