### ISSUE TITLE
Testy manualne Web - III tura

### ISSUE THREAD

**Issue by Student-ka** [Nawigacja-SGGW/Dokumentacja#50]
Treść zadania
-
- W ramach zadania należy uruchomić aplikację webową lokalnie oraz przetestować jej możliwości względem scenariuszy obejmujących funkcjonalności podstawowe. (Scenariusze od 0 do 5). Skupiamy się tutaj na użytkowniku końcowym i interfejsie.

- W zakres zadania wchodzi również zapisanie sugestii/obserwacji/uwag, wg. opinii testerów cennych dla dobra projektu.
W razie braku powyższych informacja o całkowitej poprawności z wymaganiami.
Prośba o zamieszczenie ich w komentarzu pod zadaniem.

Podział zadań (scenariuszy):
@martunia880 - 0, 4a
@agaszady - 5
@konradmal - 4b, 4c + 2aa, 2b
@HubertMarczuk - 4d
@MichalPamieta - 1b, 2a
@Dejwero - 2c
@bartoszkonarski - 1a

**Uwaga!**
-

- Do odpalenia jest konieczność stworzenia pliku o nazwie **.env.local** i wrzucenia go do katalogu **webapp**.

Niech zawartość pliczku wygląda tak:
VITE_OSMR_API_URL=https://routing.openstreetmap.de/
- Testujemy dalej na gałezi **dev**

Przydatne linki
-
Link do scenariuszy: https://docs.google.com/document/d/13LVHm4QKxIvUkFTarfHiFv_aQYFxHRLeYVQgY6VG-II/edit?tab=t.0#heading=h.bkmsbbcx2fsq
Link do figmy: https://www.figma.com/design/6C7dUvxgOpZMqRNPQcLlHV/Nawigacja---SGGW?node-id=0-1&node-type=canvas&t=VPvGzziq47ljhcl3-0
Link do repo: https://github.com/Nawigacja-SGGW/webapp

**Comment by MichalPamieta** [comment]
Uwagi ogólne - w menu na pasku bocznym, według widoków, miało być "Places", a jest "Objects". Brakuje też przycisku do zamiany punktu początkowego z punktem docelowym w wyszukiwarce nawigacji.

Scenariusz 1b - Nawigowanie
Funkcjonalność jest niedostępna. Po kliknięciu przycisku "Nawiguj", przycisk zmienia się w "Start - x min", który jest nieaktywny.
![Image](https://github.com/user-attachments/assets/5dfd227e-4257-43f1-becc-469d5c2cbd59)
![Image](https://github.com/user-attachments/assets/c7152577-d2b9-4638-9064-42e0a687b777)

Scenariusz 2a - Wyświetlanie obiektów (wraz z ich właściwościami)
Brak możliwości rozpoczęcia nawigowania z widoku obiektu ze szczegółowymi informacjami (w scenariuszu punkt 1b) Przypadek uruchomiony z funkcjonalności ‘przeglądanie obiektów z możliwością sortowania po numerze lub nazwie’).
![Image](https://github.com/user-attachments/assets/96f91599-94ce-4daf-b10a-81ecb26fdfd3)
Niewprowadzone szczegółowe informacje dotyczące obiektów (tylko placeholdery) - 
rozumiem, że wynika to z występujących problemów z bazą danych.

\* Funkcjonalności nieprzetestowane w pełni; uwagi dotyczą sytuacji, które zauważyłem podczas sprawdzania przypisanych mi scenariuszy i są z nimi powiązane.

\* Scenariusz 1a - Wyznaczanie trasy
Według scenariusza, trasa do punktu docelowego powinna być wyznaczana dopiero **PO** kliknięciu przycisku "Nawiguj" (teraz jest wyznaczana od razu po wybraniu punktu końcowego, bez dodatkowej interakcji).

\* Scenariusz 4a - Logowanie
Brak walidacji formularza - przycisk "Zaloguj się" od razu przenosi do widoku mapy (nawet w sytuacji, gdy pola login i hasło są puste).

\* Scenariusz 2c - Przeglądanie obiektów (z możliwością sortowania po numerze lub nazwie)
Przejście do widoku "Obiekty" wyświetla nieposortowaną listę obiektów, mimo że domyślnie jest zaznaczona opcja "Sortuj według: Nazwa: od A do Z".

**Comment by HubertMarczuk** [comment]
Scenariusz 4d:
punkt 1) zgodny ze scenariuszem.
punkt 1a) - nie ma możliwości sprawdzenia czy można uruchomić zmianę hasła po rejestracji (gdyż ta nie działa).
punkty 2) oraz 2a) - zgodne ze scenariuszem.
punkt 3) i 3a) - obecność wpisanego w formularz adresu e-mail w systemie nie jest sprawdzana. Po wpisaniu czegokolwiek w poprawnym formacie i kliknięciu przycisku "Wyślij e-mail" nie ma żadnej informacji zwrotnej.
![sdffsd](https://github.com/user-attachments/assets/cd7cf2bb-da38-42ec-ab26-ab0b32114d48)

punkt 4 - e-mail nie jest wysyłany, gdyż nie da się zarejestrować konta na adres e-mail, do którego mam dostęp.
punkt 5, 5a), 5aa), 5ab) 6 - brak możliwości przetestowania z racji na niedziałający elementy z punktów 3 i 4

**Comment by konradmal** [comment]
Scenariusz 4b.
Zacznę od tego, że nie wiadomo na 100%, czy użytkownik może się wylogować ze względu na to, że logowanie nie działa. Ocenię tylko wizualnie:
pkt 2. Brak okna z potwierdzeniem
pkt 3. Brak informacji o wylogowaniu po wylogowaniu

Scenariusz 4c.
pkt 2.
Po wpisaniu dwóch różnych haseł brak informacji, że są różne hasła (powinien być jakiś komunikat o tym, że są inne, jak w przypadku nieprawidłowego adresu e-mail).
pkt 4.
Brak logiki rejestracji, przycisk "zarejestruj się" nie działa.
pkt 2ab.
Nie jest sprawdzane w ogóle.
pkt 2ac.
Jak w pkt 2., czyli brak informacji.
pkt 3a.
Nie jest możliwe do sprawdzenia, bo nie rejestruje.

**Comment by Dejwero** [comment]
Scenariusz 2c:
- Obiekty nie są domyślnie posortowane alfabetycznie: checkbox "Od A do Z" jest domyślnie zaznaczony, jednak obiekty nie są na początku w ten sposób posortowane. (Scenariusz 2c. punkt 2.)

- Brak opcji sortowania po numerze (Scenariusz 2c. punkt 3aa.)

- Wyszukiwanie po nazwie działa jak należy, jednak nie ma opcji filtrowania. (Scenariusz 2c. punkt 3b.)

- Według scenariuszy, wyznaczanie trasy powinno odbywać się po wyborze punktu startowego i końcowego. Jednak ich wybór powinien prowadzić do listy wszystkich obiektów, gdzie są zdefiniowane opcje sortowania i filtrowania, a nie przez oddzielną listę. Użytkownik, chcąc wyznaczyć trasę, klika wybór miejsca i powinno przenosić go do listy obiektów (Scenariusz 2c. punkt 1a.),  a po wyborze miejsca wraca do wyznaczania trasy. (Scenariusz 2c. punkt 3c.)

**Comment by konradmal** [comment]
Scenariusz 2aa.
pkt 2.
System rzeczywiście umieszcza wybrany punkt na ekranie (nie na środku - doprecyzowanie scenariusza), ale nie wyświetla przycisku do nawigowania. Jednakże, gdy się następnie kliknie na inny obiekt, który jest oznaczony pinezką, to nawiguje z punktu zaznaczonego na mapie do obiektu oznaczonego pinezką. Nie ma opcji nawigowania pomiędzy dwoma punktami, które nie są oznaczone pinezkami.

Scenariusz 2b.
pkt 2.
Nie zawsze jest wyświetlony numer budynku i adres.
pkt 2a.
Brak informacji o braku obiektów, po prostu brak obiektów w wyszukiwarce.

**Comment by bartoszkonarski** [comment]
Scenariusz 1a:
pkt 1b: Formularz do wyznaczania punktu początkowego i końcowego jest wyświetlany cały czas od samego uruchomienia aplikacji, nie po wciśnięciu przycisku wyznaczania trasy
pkt 1c: Brak możliwości przejścia z widoku obiektów do nawigacji
pkt 1d: Brak funkcjonalności harmonogramu
pkt 2b: Brak informacji o nieudostępnionej lokalizacji
pkt 3aa: Brak możliwości zmiany punktu startowego poprzez wybór obiektu z mapy, kliknięcie na obiekt zawsze zmienia punkt docelowy
pkt 3ab, 3bb: Lista wszystkich obiektów jest listą rozwijaną, nie jest uruchamiana fukncjonalność 'przeglądanie obiektów'
pkt 3c: Brak możliwości zamiany miejscami punktów początkowego i końcowego

**Comment by agaszady** [comment]
5. Ustawianie wersji językowej - tłumaczenie działa (zarówno przełączanie w menu jak i w ustawieniach). Nazwy obiektów i szczegóły nie są tłumaczone, ale rozumiem, że tak miało być
![Image](https://github.com/user-attachments/assets/d1d58f53-5c9d-4593-baf5-fe9f9337fa5d)

**Comment by martunia880** [comment]
Scenariusz 0: **1a)** OK
**2a)** 1. Nie działa jeszcze logowanie (można się zalogować bez wpisywania danych), rejestracja i zapomniałeś hasła również nie działa (rozumiem że jeszcze funkcjonalność nie jest skończona). 
2. Jeśli chodzi o interfejs brakuje mi przycisku na ekranie do rejestrowania się żeby jednak się przełączyć na ekran do logowania (coś w stylu: Masz już konto? Zaloguj się).
3. Na ekranie do zmiany hasła, po wysłaniu nowego hasła na maila powinien wyskoczyć komunikat, że jeżeli istnieje konto na podanym adresie e-mail to nowe hasło zostało wysłane i powinien być przycisk do powrotu ekranu do zalogowania się.
**2b)** Podczas rozłączenia się z internetem nie wyświetlił się żaden komunikat
**2c)** Taki komunikat to chyba powinien się wyświetlić dopiero po zalogowaniu się (jak jest włączona mapa) po kliknięciu wyświetl moje położenie (przynajmniej na innych mapach webowych tak to działa)- btw nie wyświetlił mi się taki komunikat. 
**2d)** OK

**Comment by martaguza** [comment]
Scenariusz 0: 1a) OK
2a) 1. Nie działa jeszcze logowanie (można się zalogować bez wpisywania danych), rejestracja i zapomniałeś hasła również nie działa (rozumiem że jeszcze funkcjonalność nie jest skończona).
2. Jeśli chodzi o interfejs brakuje mi przycisku na ekranie do rejestrowania się żeby jednak się przełączyć na ekran do logowania (coś w stylu: Masz już konto? Zaloguj się).
3. Na ekranie do zmiany hasła, po wysłaniu nowego hasła na maila powinien wyskoczyć komunikat, że jeżeli istnieje konto na podanym adresie e-mail to nowe hasło zostało wysłane i powinien być przycisk do powrotu ekranu do zalogowania się.
2b) OK
2c) Taki komunikat to chyba powinien się wyświetlić dopiero po zalogowaniu się (jak jest włączona mapa) po kliknięciu wyświetl moje położenie (przynajmniej na innych mapach webowych tak to działa)- btw nie wyświetlił mi się taki komunikat.
2d) OK

Scenariusz 4a) jw (Scenariusz 0 podpunkt 2a)
